language: node_js

cache:
  directories:
    - ~/.npm

notifications:
  email: false

node_js:
  - 11
  - 10
  - 9
  - 8

after_success:
  - npm run report

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
