language: node_js
cache: yarn
node_js:
  - node
  - '10'
  - '8'

os:
  - linux
  - osx

branches:
  only:
    - master
    - /^greenkeeper/.*$/

script:
  - npm test

after_success:
  - yarn coverage

jobs:
  include:
    - stage: release
      if: branch IN (master, next)
      node_js: node
      script:
        - npm run build
        - npx semantic-release
      env:
        - secure: wJkAB5oJClOYrw3PV01Y4GJqXAz8AxEuCS3yHrlIXn8QYEWAQdZPdReFhp+ECMcPYDb9nxPTRAaoM6X7d7FeC1mct7Pp6yVobMuBPo7KcqgHM4/cB4sL3Du2UlxAK6YxrLHF/osnBr7ci5ule+alfGXYQxbt7hWP6ep55t8cWVcqpTBuhCEif+eSRJCpg68j0vrRJYwGq0SPXlbULwVPhAgu8Rerq+/iTEbT8EulvIOS1AlYvKE6Nme5sSaVN17s2wgf3y+nWYXj734bepRu/rXq2C3mZ+mgNtaPHBG+EeJhm3soc1rjQN1pf9hs/RDhgWBKF/OUUZaboB5XW+mNmArKu9A7Dd88fImpmgwsmkURSeHK7R7n/jd/VeZe+gwheMDDPJbmP/kflb1kTUmWq5wVRdo9DMCNoZxuLYlARZo0dR+YT4OrjzUVnk7Swh7rmTqlhj47Q756CJJhJcyynj+01tdWexkqyn6J/DGjr+gR7M5B0rOe4JPolQnV/3P8rUTsJoeSQ8FQ0gRNRWQqV5ubVngMfXMXgu8gHQiBTN0WuQDmWIP1TaD6J2VVONt/sKq/BfnHOFGEsSdmhnoX4k14AQNoIGKsT4UxcXaDLIO+7d6MTrVIHicpdzja/w+aLDi9zZd/S3ZmLqjsKCUxyknc8E+IEiuOs0Mr9tw205s=
        - secure: OG9952PTWmz5wQo3A40gyVZwm9gG4LKmyZS6Xjj81Q8qNEhQ3M+ikQM8d8OWZZtQLAmXyZJKE0pZC40j55Be5eOi//Fqum0+ZuUhe7gdzTmTczg3VwYbaGXPm1O40fKuivjppgw/2NclunLuwaBcrq0zRGZLnnr4Olje5K7wL9ur+MLMqcfUQMOcIDYBuXbc1l+ihrpIMpUJ1WtGJ6Soa+REZu9Jf0dhklBZw6jD+J0FNDrrIahLYBESCrHA/P7GXIEula1PmLCpFMt33oDJiMbeuerZ0BtgmIbjTKOENUbvuneUAuk9Bdg+LBO80/Qzfkjzqw9qs0MEkzEzoFEqli5mmOFPycCW3KZ+8nYWu/A2CPyPg0VHHP92rSz2UAzIqFPzM1DedvtA3wbwDjnrZHAyqu8vT4Z0ypWgtbydT2F8wlh9fvWj+/7M2CFZl/CPpph+dSOzypPTwI6iu3RfunTy5zC5NROr3VZp6mY3gKsXHDLLWXzyOONbuoIoipmB2rb616FaHkIj5lUDOr+TexzVdamGkbTF+8L9O96Hb5GJJmTDtNUtkZruPnTX0VXR2/8Hld7MIGq41567EuD3ve/MmeZBqmsZ5niptU1LJQXEkNswbzQhVE+3f5M6WawUnpOxpy5C/Jz61jNQ/wQ8nr1+46hixuMeTEUcOs9bfq4=
