language: node_js
cache: yarn
node_js:
  - node
  - '10'
  - '8'
os:
  - linux
  - osx
branches:
  only:
    - master
    - '/^greenkeeper/.*$/'
script:
  - npm test
after_success:
  - yarn coverage
jobs:
  include:
    - stage: release
      if: branch IN (master, next)
      node_js: node
      script:
        - npm run build
        - npx semantic-release
      env:
        - secure: 0PTkefim1bMIg6wE2uSa662DCZg7N4bpNK/3HDJRk2H4CNpPWvMK6l8y7fP9hj7d3k4bUMJkKasdJND1P4/TyZM/UuV6KXQaO14rs2iuZsfL4q+x1IpmgZtR0rIpHiV52URGZJPVTOfIOs9wJFxyNxXeLq5dadiSoQ7zOgxnuk3nm3aTZUTC7DxXoz3bsRjPXlNnUjWYI/dbBl8BR41yte5qo5DChnn63XVm+hybSvUbJ/cHiUtbJPpMWHILKYLYLJwhP9s5SZ9YkLgBIVTlJtXMs9wOrbfB3+MLddsz35kHs4lz9IIfhdb11o5LrXAoKPlXdQPP4X6NVmKEehE8tQ8YrCpWHRtLrw6Z8UVnd7b/ZKrCeErmcAFLh0NgSMGNDXJtpV8QHz+4/vMISZKeYocpOof6ohUG9QrAYMJlkOkovgL2YXjmFPYmY0vl41mk+2RxcDVP8dmD/TqFFYut5Q9ulzqRi43PIG7JE4cdpk+CU7hffTbeZs7NeapgHwoSLJPGbPVBHbjznDpaZk4a5xY++abaX58Q9Z7leKIihleXxS6O3W0TqfZdEBC8oBBMrmG9UF1dSCUm1LpMCFBa7YDL96HAOH4bge5lBweKJmmd5CqzARl2u9nxy2nbePRXiNP0rRphx5P1zhmxMFDt551Tmz5whGBCUgVfOkjvW70=
        - secure: y3IgwsmDSGU5ZbaZDajBM0fwIRZpXveBMXx49ymNpYIQ0mOM/1v2Hyt7ZK51doT+a+v4kwy4Ahzuv0v7H0oQNZK6fpv4uA5burKCYah4lovYLgg8Dqhc1VK2nX5WR5g2ambvaKoD0M9kwdX/X6F4JJbVOS+97zpgQZVEB19vn83JpgdrUQR33NeiaMflWxQfJq4JUo2+5DXkGOWYX/RstKsewRV4nWuCan8u1cMZdvVcUleSJnEOyIYWWCZnMT50J5DHqNMMePUIC8Hwd9HiWRQ4h/vfHPIxW1joHtQvCa/anh7mRHWGle2cFH/5rX/2bwuerriWLiNw/XGpRc5ItHuk6/scGsDY8lBJISgV6FNM4dWssBHkWoh4zVHoggVT79Q1W1Q70XePUcdlopIudWPfRcLX2OujIotr4BaFZPXopn5rshU/43AczrGDzDgN7JQNRDcQlrHEp67Wo5GImyelQtEWXtErw371mWaeXArcV6g4ZCVrNf5TuDqKqbdw+ju/d2ny5yKz7RQrATkR5pxIUYM5m2RRkywGXtIPZph1D7dtzrW1siyaBCMOSYcFUgaTVHwCSggFCX003A0Ne9oi33Vq+eZhfIrD4RJBtNcga1VrneniJTyfaYMVUnzzXbRf81DVuSaIiMxweQBq84QNgwRybXWXI0RbiCqvZ6w=
