language: node_js
cache: yarn
node_js:
  - node
  - '10'
  - '8'

branches:
  only:
    - master

after_success:
  - yarn coverage

jobs:
  include:
    - stage: release
      node_js: lts/*
      script:
        - npm run semantic-release
