language: node_js
cache: yarn
node_js:
  - node
  - '10'
  - '8'
os:
  - linux
  - osx
branches:
  only:
    - master
    - '/^greenkeeper/.*$/'
script:
  - npm test
after_success:
  - yarn coverage
jobs:
  include:
    - stage: release
      if: branch IN (master, next)
      node_js: node
      script:
        - npm run build
        - npx semantic-release
      env:
        - secure: 0PTkefim1bMIg6wE2uSa662DCZg7N4bpNK/3HDJRk2H4CNpPWvMK6l8y7fP9hj7d3k4bUMJkKasdJND1P4/TyZM/UuV6KXQaO14rs2iuZsfL4q+x1IpmgZtR0rIpHiV52URGZJPVTOfIOs9wJFxyNxXeLq5dadiSoQ7zOgxnuk3nm3aTZUTC7DxXoz3bsRjPXlNnUjWYI/dbBl8BR41yte5qo5DChnn63XVm+hybSvUbJ/cHiUtbJPpMWHILKYLYLJwhP9s5SZ9YkLgBIVTlJtXMs9wOrbfB3+MLddsz35kHs4lz9IIfhdb11o5LrXAoKPlXdQPP4X6NVmKEehE8tQ8YrCpWHRtLrw6Z8UVnd7b/ZKrCeErmcAFLh0NgSMGNDXJtpV8QHz+4/vMISZKeYocpOof6ohUG9QrAYMJlkOkovgL2YXjmFPYmY0vl41mk+2RxcDVP8dmD/TqFFYut5Q9ulzqRi43PIG7JE4cdpk+CU7hffTbeZs7NeapgHwoSLJPGbPVBHbjznDpaZk4a5xY++abaX58Q9Z7leKIihleXxS6O3W0TqfZdEBC8oBBMrmG9UF1dSCUm1LpMCFBa7YDL96HAOH4bge5lBweKJmmd5CqzARl2u9nxy2nbePRXiNP0rRphx5P1zhmxMFDt551Tmz5whGBCUgVfOkjvW70=
        - secure: oBenL6oPcqBpatS4jySQO4hMfb9uqK7FC20b8VY4PA0SksUgxRNGgyW4QwZFVcm89+PAWnGuVRnUVYMpn0pgTqk0KNAObtkeqJEyQ6R9eTaLql30U99jTiT7x45IPWjika+UBoAeetq/QczWNeq2/+PQx8uZgvZwMWaYkW7wxfatecarE2N40pVI4Q771iYHSYnc6qRnqfxLxacuM9XgPFZmU8YN1rSkOpgSyPPYl/QFS0m4EubWy5pDGGWT9dOyhm5602IDh//zRBuK/vSJRN03pZTrX9qqERzrIWZ8bsgtFKzs/AUHUS/BBzshTzKgNNd1xF9dn5lCdZ+cOESZel9ZaVIsUgTo2CPuaNGdJmtnMz3lJpWW+OsMnhzskaNTZ+EUhf7Y21HmQpkf+zui4UtFXTXtQ88NbTWeHQ9ihEZNfbhxSoW3C4YCiwvKAtt9S0dRR1Vc6JTYmGbhbgee9XNXWwC4ugojhAQdLLcsz8/v1Ifncsv+0NCL9Yx4pSUEss8xO9OGy3xKgOT6ujNJU5n/9z2SoBL8Mx09TL5x+KQefAq9A3GaUv1NtxECiW41dpOdR5Dm0Bi/FYSNxsfAyoLChOxvRSwz7Sm3fGo1js+ewh32Dux1R9y7MEAaeQplI/N7yGPOM9nMc4U2qib6BnS1M0T2FEzcuPUG16Vc1C8=
