exports.HALF = 0.5;
exports.BROWSER_VIEWPORT_WIDTH = '100vw';
exports.BROWSER_DEFAULT_FONT_SIZE = 16;
exports.POSITIVE_OR_NEGATIVE_INT_OR_FLOAT_NUM_AT_BEGINNING_OF_THE_STRING = /^-?\d+(\.\d+)?$/;
exports.DASH_HYPHEN_WHITESPACE_ANY_CHARACTERS = /[-_\s]+(.)?/g;
exports.SEPARATE_STRING_INTO_WORDS_WITH_CAPITAL_LETTER = /(?=[A-Z])/;
